_base_ = ['yolo_uniow_l_lora_bn_1e-3_20e_8gpus_owod.py']

# FOOD VOC-COCO — T1 base training config.
# Override embedding paths to use FOOD_VOCCOCO-specific embed directory.
# Embeddings are generated by: tools/owod_scripts/extract_embeddings.py --dataset FOOD_VOCCOCO
model = dict(
    embedding_path=f'embeddings/uniow-food-voccoco/{_base_.owod_dataset.lower()}_t{_base_.owod_task}.npy',
    unknown_embedding_path='embeddings/uniow-food-voccoco/object.npy',
    anchor_embedding_path='embeddings/uniow-food-voccoco/object_tuned.npy',
)
